dist: xenial
language: node_js
node_js:
  - "lts/*"

services:
  - docker

env:
  global:
    - AWS_DEFAULT_REGION=ap-northeast-1

cache:
  yarn: true

install:
  - pyenv install -s 3.7.1
  - pyenv global 3.7.1
  - pip install awscli --user
  - yarn

before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID};
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY};

# script:
#   - npm run lint
#   - npm run test

before_deploy:
  # Set master branch variables
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID};
      export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY};
      export TASK_DESIRED_COUNT="1";
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy-app.sh demo-cluster web-service web
    on:
      branch:
        - master
