dist: xenial
language: node_js
node_js:
  - "lts/*"

services:
  - docker

cache:
  npm: true

install:
  - pyenv install -s 3.7.1
  - pyenv global 3.7.1
  - pip install awscli --user
  - npm

before_script:
  - export AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID};
  - export AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY};

# script:
#   - npm run lint
#   - npm run test

before_deploy:
  # Clear AWS credentials
  - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCOUNT_ID
  # Set master branch variables
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      export AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID};
      export AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY};
      export TASK_DESIRED_COUNT="1";
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy-app.sh demo-cluster web-service web
    on:
      branch:
        - master

notifications:
  email:
    on_success: never
  slack:
    on_success: never
    rooms:
      secure: f20kIFeWtfZ+IU/tTGzsEi2X2LWuvAwbZsxd43iA3jw16s3ayPjph5HphqrdciPwNp62t/bY6KNu5m1jLXOSrHHkqo3wtTyZ8ZCgh+FUcb0C/t3YGLc7gdG8Hy82yfph7UIZ5LpBaXsy99HY06YHZx+ssSQQHfQykkf771CRonghXRw0s2tCe8zdEjFSr8o40KGHndiRrADMxCUhwDScVTf7iezAMKYwYfyeRbAvUx/5u7wq5+nyPyR0PPixh7dcXy8sasSLamJLyHahnCjITr4BUFwawvFQKhqyYBsKExKB7cfQ1WJLotPoOrUT7DwiB5CbbNrVTBhRqMuLyLXOUm09p1MzMQIZRZCHfCtSFlgshT14K3Gqn4DCe32FoEGXvpZhOCDisl/fU+guYJnKLfQOpjNQuUhkKtX0a3L/Nbz5FnRwl4eupcAZWGcv7xbAH23qGn4Vue48KAfuVZRx95kHOhpN34mrf9/o4HGSRoQsKivfBalVS+5kxgzusafRqn6ZLqfP/9Zt0BmqpLOwToKRK8U3hp/6tXxrQxxO/FbWeJsL9yo5IuRsVdTFPlu52gHHwvrjhsIMoBQ1zoEDi0ZS8aDrcpjIGrA1QMo7veWu+IeWvC3aETX6lsWK+4E46kh4PFYouHnZc/Cw8+M0tqt0rMCqfYWAyvT+2Jl4868=
